### PR TITLE
Fix issues with membership

### PR DESCRIPTION
**Pull request by dirkmc**
Several fixes to membership, with accompanying tests.
Note: the tests will not all pass until https://github.com/ipfs-shipyard/js-delta-crdts/pull/23 is merged
Note also that I found another bug in ormap that I have [included a test for](https://github.com/ipfs-shipyard/peer-star-app/pull/112/files#diff-9697b8ec03600bdf064c345c915b586fR228) in membership.spec.js (the test is currently skipped). I need to move the test to js-delta-crdts and investigate the root cause.

### CODE REVIEW

**Comment by pgte** [comment]
@dirkmc looks good!
delta-crds v0.5.3 is now released with that fix.

**Comment by dirkmc** [comment]
@pgte great, thank you!

I have a question, why did you change the membership gossip such that it will now always send a summary message alongside the full message? Convergence seems to proceed as expected if I send just the full message (without the summary message) in the tests and in the simulator.

**Comment by pgte** [comment]
@dirkmc I think that's there only for historical reasons, feel free to remove it.

**Comment by dirkmc** [comment]
@pgte ok great, I've removed it and added a few more tests, I think this PR is good to go

**Comment by dirkmc** [comment]
Note that this PR fixes a possible flooding issue where `gossip now` events would pile up between the time membership was started and the time IPFS was started. I'm not sure how common a case that is but this PR should take care of it, maybe it will help with the flooding issues @jimpick was seeing

**Comment by pgte** [comment]
Loads of membership fixes here, thanks @dirkmc!

**Pull request merged**
