### PR TITLE
Suppress aegir eslint warnings

### PR DESCRIPTION
**Pull request by jimpick**
Most of the warnings could be eliminated, but it would be good
to discuss a strategy on a case-by-case basis. For example,
we do a lot of console logging for errors, but those should
probably be passed up so that the UI can handle them.

I propose that we suppress the warnings for now, and then file
some github issues so we don't suppress the warnings forever ...
eg. "remove console.log statements in collaboration/gossip", etc.

### CODE REVIEW

**Comment by dirkmc** [comment]
I feel like the solution here might be to add a configurable logger - they do this for example in the floodsub module:
https://github.com/libp2p/js-libp2p-floodsub/blob/master/src/config.js

**Comment by dirkmc** [comment]
@pgte I'm not sure I follow - are you saying we should have structured log output?

**Comment by pgte** [comment]
@dirkmc would this strategy of injecting a logger require us to parse the logger output?

**Comment by dirkmc** [comment]
I don't think so.. I think we could just do what they do in floodsub and use debug (or some other logging module)

**Comment by pgte** [comment]
@dirkmc sorry, I was following the conversation through email and I mixed my issues. Nevermind what I said about the logger, I thought you were talking about observability of floodsub events! 😂

**Comment by dirkmc** [comment]
haha no worries :)

**Pull request merged**
