### PR TITLE
WIP: speed-up tests

### PR DESCRIPTION
**Pull request by pgte**
...by:

- [x] replacing some timeouts with event-driven waiting for membership
- [x] replacing some timeouts with event-driven waiting for shared value

### CODE REVIEW

**Comment by pgte** [comment]
Fixes #118

**Comment by dirkmc** [comment]
This is great! Faster tests mean people will run the tests more often and catch bugs.
I did something similar in the persistence tests, there may be some code you can reuse there:
https://github.com/ipfs-shipyard/peer-star-app/pull/75/files#diff-458151130519ebd1248814f22515eb52R241

**Comment by dirkmc** [comment]
For some tests (eg the membership tests) we can also speed them up a lot by passing an option to set the sample interval to some low number (eg 100ms)

**Comment by pgte** [comment]
@dirkmc I think we can make most of them event-driven, without needing to poll.

**Pull request merged**
