### PR TITLE
Feat/sim

### PR DESCRIPTION
**Pull request by dirkmc**
Network simulator for peer-star applications
- Display dias set connections between peers
- Debug membership gossip and convergence
  - Test timing and adding / removing nodes
  - Logs time to converge (since first and last change)
  - Modify options in real time

2 minute video showing these features
https://www.youtube.com/watch?v=3OZqLg9iu9w&feature=youtu.be

I'm opening this PR so that other people can use the simulator. @pgte I'm not sure if it makes most sense to include it in peer-star-app or as a standalone project?

### CODE REVIEW

**Comment by lanzafame** [comment]
A reset to default values button would be useful :+1:

**Comment by pgte** [comment]
@dirkmc this is awesome!

It uses the internals(membership object) so I think that for now it's ok for this to remain in this repo for the time being.

I've created [this issue](https://github.com/ipfs-shipyard/peer-star-app/issues/115) to address this in the future.

Could you add some instructions? For instance, you could add a `docs/MEMBERSHIP_SIM.md` document, linked in the `README.md`.

**Comment by dirkmc** [comment]
@lanzafame good idea I will add one 👍 

@pgte I will add a README

I also have leadership election ready to integrate, however I imagine that for different use cases people will want to use different strategies (eg pinner vs leadership + persistence). So I'm thinking maybe it makes sense to build some kind of plugin system, where a module can listen for certain events and implement hooks (eg leadership needs to add its own information to gossip messages)

**Comment by dirkmc** [comment]
I think this should be good to go. Once it is merged in I will create a PR for the leadership work I've been doing (I updated the simulator to support leadership in that branch so it depends on this PR)

**Comment by pgte** [comment]
This is awesome, thank you @dirkmc!

**Pull request merged**
